name: phased
description: Simplified state management focused on animations
repository: https://github.com/erickzanardo/phased
version: 0.0.2

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.7'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
